#!/bin/bash

set -e

cidfile=$1
[ -z "$cidfile" ] && {
    echo "Missing arg"
    exit 1
}

# print list of GPU devices
devicelist_gpu()
{
  find /dev/dri/* /dev/nvidia* /dev/vga_arbiter /dev/nvhost* /dev/nvmap -maxdepth 0 -type c 2>/dev/null ||:
}

# print list of input devices
devicelist_input()
{
    find /dev/input/* -maxdepth 0 -type c 2>/dev/null ||:
}

append_gpu_opts()
{
    local gpudevice=''

    while read -r gpudevice ; do
        echo " --device $gpudevice:$gpudevice "
    done < <(devicelist_gpu)
}

append_input_opts()
{
    local inputdevice=''

    while read -r inputdevice ; do
        echo " --device=$inputdevice "
    done < <(devicelist_input)
}

vgadev=$(lspci | grep -i "VGA compatible controller")
gpudriver=""

if [[ $vgadev == *"Alder Lake-N"* ]]; then
    echo "Alder Lake-N (UHD Graphics) detected, using default modsetting driver"
    gpudriver="--modsetting"
fi

## Other hardware workaround can be added here later

cconf=$(podman exec calaos-server /opt/bin/calaos_config get gpu_modsetting)
if [[ $cconf == "true" ]]; then
    echo "Modsetting driver forced by calaos_config"
    gpudriver="--modsetting"
elif [[ $cconf == "false" ]]; then
    echo "Intel driver forced by calaos_config"
    gpudriver=""
fi

# shellcheck disable=SC2046

podman run \
        --name=calaos-home \
        --cidfile="${cidfile}" --replace --rm --tz=local \
        --sdnotify=conmon -d \
        -v /mnt/calaos/cache:/root/.cache/calaos/ \
        -v /mnt/calaos/config:/etc/calaos \
        -v /run/calaos:/run/calaos \
        --tty \
        --tmpfs /run:exec \
        --tmpfs /run/lock \
        --tmpfs /tmp \
        --network=host \
        --pull=never \
        --replace \
        --tz=local \
        --mount type=bind,source=/run/dbus,target=/run/dbus \
        --mount type=bind,source=/run/udev/data,target=/run/udev/data,readonly \
        $(append_gpu_opts) \
        $(append_input_opts) \
        "${IMAGE_SRC}" \
        /usr/bin/start.sh "$gpudriver"
