#!/bin/bash

set -e

NOCOLOR='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHTGRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
LIGHTPURPLE='\033[1;35m'
LIGHTCYAN='\033[1;36m'
WHITE='\033[1;37m'

green()
{
    echo -e "${LIGHTGREEN}$*${NOCOLOR}"
}

info()
{
    echo -e "${CYAN}$*${NOCOLOR}"
}

warn()
{
    echo -e "${ORANGE}$*${NOCOLOR}"
}

err()
{
    echo -e "${LIGHTRED}$*${NOCOLOR}"
}

pkgname=$1
pkgversion=$(echo $2 | tr - _)
image_src=$3
workdir="/work"

cd $workdir || exit

git config --global --add safe.directory $workdir

if [ -z "$pkgversion" ]
then
    err "Version not specified"
    exit 1
fi

cd /work/$pkgname

sed -i "s/VERSION = 1.2.3/VERSION = $pkgversion/g" debian/rules
sed -i "s/1.2.3/$pkgversion/g" debian/changelog
sed -i "s/VERSION?=.*$/VERSION?=$pkgversion/g" Makefile

if [ -n "$image_src" ]
then
    sed -i "s/IMAGE_SRC?=.*$/IMAGE_SRC?=$image_src/g" Makefile
fi

pkg_name=$(grep "Package: " debian/control | sed 's/Package: //')

apt-get build-dep -y .
dpkg-buildpackage -us -uc -b
lintian ../"${pkg_name}"_*.deb

make clean

mkdir -p $workdir/pkg
mv ../"${pkg_name}"_*.deb $workdir/pkg

green "Build with success!"