#!/bin/bash

set -e

cidfile=$1
[ -z "$cidfile" ] && {
    echo "Missing arg"
    exit 1
}

fs="/mnt/calaos/hue2mqtt"

# shellcheck disable=SC2046

podman run \
        --name=hue2mqtt \
        --cidfile="${cidfile}" --replace --rm --tz=local \
        --sdnotify=conmon -d \
        -v /mnt/calaos/hue2mqtt:/config \
        --network=host \
        --pull=never \
        --replace \
        --tz=local \
        ${IMAGE_SRC}
