#!/bin/bash

set -e

cidfile=$1
[ -z "$cidfile" ] && {
    echo "Missing arg"
    exit 1
}

fs="/mnt/calaos/hue2mqtt"

devlist()
{
    grep '/dev/' ${fs}/hue2mqtt.toml | awk '{print $2}'
}

append_dev_opts()
{
    local device=''

    while read -r device ; do
        echo " --device $device "
    done < <(devlist)
}

# shellcheck disable=SC2046

podman run \
        --name=hue2mqtt \
        --cidfile="${cidfile}" --replace --rm --tz=local \
        --sdnotify=conmon -d \
        -v /mnt/calaos/hue2mqtt/hue2mqtt.toml:/hue2mqtt.toml \
        --network=host \
        --pull=never \
        --replace \
        --tz=local \
        $(append_dev_opts) \
        ${IMAGE_SRC}
