name: Repository Dispatch

on:
  repository_dispatch:
    types: [build_deb]

jobs:
  buildEvent:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: make-deb-${{ github.event.client_payload.pkgname }}
        run: make build-${{ github.event.client_payload.pkgname }} PKGVERSION=${{ github.event.client_payload.version }} IMAGE_SRC=${{ github.event.client_payload.image_src }}
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: deb
          path: pkg/*.deb

      - name: Create a Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.CALAOS_REL_TOKEN }}
          tag: ${{ github.event.client_payload.pkgname }}-${{ github.event.client_payload.version }}
          name: ${{ github.event.client_payload.pkgname }} - ${{ github.event.client_payload.version }}
          prerelease: ${{ github.event.client_payload.prerelease == true }}
          files: pkg/*.deb
          gzip: false

      - name: Update repo cache
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: ${{ secrets.DEB_REPO_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.DEB_REPO_WEBHOOK_SECRET }}
